[package]
edition = "2021"
name = "helloext"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
freeverb = "0.1"
godot = {git = "https://github.com/godot-rust/gdext", branch = "master"}
