name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 8 * * *"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GODOT_VERSION: 4.1.2-stable

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - run: curl -v -o godot.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_linux.x86_64.zip
  #     - run: unzip godot.zip
  #     - run: curl -v -o templates.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
  #     - run: unzip templates.zip "templates/macos.zip" "templates/windows_release_x86_64*" "templates/version.txt"
  #     - run: mkdir -v -p ~/.local/share/godot/templates/$(cat templates/version.txt)
  #     - run: mv templates/* ~/.local/share/godot/templates/$(cat templates/version.txt)/
  #     # - run: Godot.app/Contents/MacOS/Godot -v --export-release --headless "macOS" Godottest.dmg
  #     - run: ls -la

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: curl -o godot.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_macos.universal.zip
      - run: unzip godot.zip
      - run: curl -o templates.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
      - run: unzip templates.zip "templates/macos.zip" "templates/version.txt"
      - run: mkdir -v -p /Users/runner/Library/Application\ Support/Godot/export_templates/$(cat templates/version.txt)
      - run: mv templates/macos.zip /Users/runner/Library/Application\ Support/Godot/export_templates/$(cat templates/version.txt)/macos.zip
      - run: Godot.app/Contents/MacOS/Godot -v --export-release --headless "macOS" Godottest.dmg
      - run: ls -la

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: curl -o godot.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_win64.exe.zip
      - run: unzip godot.zip
      - run: curl -o templates.zip -L https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
      - run: unzip templates.zip "templates/windows_release_x86_64*" "templates/version.txt"
      - run: mkdir -p C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/$(cat templates/version.txt)
      - run: mv templates/windows_release_x86_64.exe /Users/runner/Library/Application\ Support/Godot/export_templates/$(cat templates/version.txt)/windows_release_x86_64.exe
      # - run: ./Godot_v${{env.GODOT_VERSION}}_win64_console.exe --help
      - run: ./Godot_v${{env.GODOT_VERSION}}_win64_console.exe -v --headless --export-release "Windows Desktop" Godottest.exe
      # - run: ./Godot_v${{env.GODOT_VERSION}}_win64.exe --help
      # - run: ./Godot_v${{env.GODOT_VERSION}}_win64.exe -v --headless --export-release "Windows Desktop" Godottest.exe
      - run: ls
