name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 8 * * *"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GODOT_VERSION: 4.1.2-rc1

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: curl -o godot.zip https://github.com/godotengine/godot-builds/releases/download/$GODOT_VERSION/Godot_v$GODOT_VERSION_macos.universal.zip
      - run: unzip godot.zip
      - run: curl -o templates.zip https://github.com/godotengine/godot-builds/releases/download/$GODOT_VERSION/Godot_v$GODOT_VERSION_export_templates.tpz
      - run: unzip templates.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: curl -o godot.zip https://github.com/godotengine/godot-builds/releases/download/$env:GODOT_VERSION/Godot_v$env:GODOT_VERSION_win64.exe.zip
      - run: unzip godot.zip
      - run: curl -o templates.zip https://github.com/godotengine/godot-builds/releases/download/$env:GODOT_VERSION/Godot_v$env:GODOT_VERSION_export_templates.tpz
      - run: unzip templates.zip
